---
title: "Analysis"
author: "Shakir Suleimanov"
date: "2024-03-26"
output: 
  html_document:
    #css: styles.css
    latex_engine : xelatex
    df_print: default
    highlight: zenburn
    toc: TRUE
    toc_depth: 4
mainfont : NanumGothic    
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Imports
```{r message=FALSE, warning=FALSE, include=FALSE}
source('../R/samples_comparison.R')
source('../R/plotting.R')
source('../R/emptyDrops_filtering.R')
```


### Datapaths
```{r paths, echo=TRUE, message=FALSE, warning=FALSE}
counts <- c(
            '../Data/3.STAR/Fixed_fresh_K562_noPEG_R1/Solo.out/GeneFull/raw/matrix.mtx',
            '../Data/3.STAR/Fixed_fresh_K562_noPEG_R2/Solo.out/GeneFull/raw/matrix.mtx',
            '../Data/3.STAR/Fixed_fresh_K562_PEG_R1/Solo.out/GeneFull/raw/matrix.mtx',
            '../Data/3.STAR/Fixed_fresh_K562_PEG_R2/Solo.out/GeneFull/raw/matrix.mtx',
            '../Data/3.STAR/Fixed_frozen_K562_noPEG_R1/Solo.out/GeneFull/raw/matrix.mtx',
            '../Data/3.STAR/Fixed_frozen_K562_noPEG_R2/Solo.out/GeneFull/raw/matrix.mtx',
            '../Data/3.STAR/Fixed_frozen_K562_PEG_R1/Solo.out/GeneFull/raw/matrix.mtx',
            '../Data/3.STAR/Fixed_frozen_K562_PEG_R2/Solo.out/GeneFull/raw/matrix.mtx')

genes <- c(
            '../Data/3.STAR/Fixed_fresh_K562_noPEG_R1/Solo.out/GeneFull/raw/features.tsv',
            '../Data/3.STAR/Fixed_fresh_K562_noPEG_R2/Solo.out/GeneFull/raw/features.tsv',
            '../Data/3.STAR/Fixed_fresh_K562_PEG_R1/Solo.out/GeneFull/raw/features.tsv',
            '../Data/3.STAR/Fixed_fresh_K562_PEG_R2/Solo.out/GeneFull/raw/features.tsv',
            '../Data/3.STAR/Fixed_frozen_K562_noPEG_R1/Solo.out/GeneFull/raw/features.tsv',
            '../Data/3.STAR/Fixed_frozen_K562_noPEG_R2/Solo.out/GeneFull/raw/features.tsv',
            '../Data/3.STAR/Fixed_frozen_K562_PEG_R1/Solo.out/GeneFull/raw/features.tsv',
            '../Data/3.STAR/Fixed_frozen_K562_PEG_R2/Solo.out/GeneFull/raw/features.tsv')

barcodes <- c(
            '../Data/3.STAR/Fixed_fresh_K562_noPEG_R1/Solo.out/GeneFull/raw/barcodes.tsv',
            '../Data/3.STAR/Fixed_fresh_K562_noPEG_R2/Solo.out/GeneFull/raw/barcodes.tsv',
            '../Data/3.STAR/Fixed_fresh_K562_PEG_R1/Solo.out/GeneFull/raw/barcodes.tsv',
            '../Data/3.STAR/Fixed_fresh_K562_PEG_R2/Solo.out/GeneFull/raw/barcodes.tsv',
            '../Data/3.STAR/Fixed_frozen_K562_noPEG_R1/Solo.out/GeneFull/raw/barcodes.tsv',
            '../Data/3.STAR/Fixed_frozen_K562_noPEG_R2/Solo.out/GeneFull/raw/barcodes.tsv',
            '../Data/3.STAR/Fixed_frozen_K562_PEG_R1/Solo.out/GeneFull/raw/barcodes.tsv',
            '../Data/3.STAR/Fixed_frozen_K562_PEG_R2/Solo.out/GeneFull/raw/barcodes.tsv')

filenames <- c(
            'Fixed_fresh_K562_noPEG_R1',
            'Fixed_fresh_K562_noPEG_R2',
            'Fixed_fresh_K562_PEG_R1',
            'Fixed_fresh_K562_PEG_R2',
            'Fixed_frozen_K562_noPEG_R1',
            'Fixed_frozen_K562_noPEG_R2',
            'Fixed_frozen_K562_PEG_R1',
            'Fixed_frozen_K562_PEG_R2')
```


### Summary metrics for UMI distribution between samples before filtering with EmptyDrops
```{r no filtering, echo=TRUE, fig.height=8, fig.width=10, message=FALSE, warning=FALSE}
# Read the samples and create a merged table for all samples
experiments_no_filtering <- read_10X_samples(counts, barcodes, genes, 
                                filenames, emptydrops_run = FALSE, fdr_threshold = 0.05)

# Calculate distribution in each barcode
experiments_no_filtering <- calculate_distributions(experiments_no_filtering, number_of_samples = 8)

# Calculate UMI proportion distribution
UMI_proportion_distribution <- calculate_umi_proportion_by_samples(experiments_no_filtering)

# Perform multinomial testing to test the departure of the UMI distribution from the reference distribution
experiments_no_filtering <- multinomial_testing(experiments_no_filtering, number_of_samples = 8, probs = UMI_proportion_distribution)

# Create a data of p-values for barcodes
pvals <- experiments_no_filtering$non_filt_pvals

# Intersection plot
intersect_plot_no_filtering <- plot_intersections(experiments_no_filtering, min_intersection_size = 2000)

# Boxplot of distributions
bp_distributions_no_filtering <- plot_distributions_boxplots(experiments_no_filtering, number_of_samples = 8, alpha = 0.01)

# Density plot of distributions
dp_distributions_no_filtering <- plot_distributions_density(experiments_no_filtering)

intersect_plot_no_filtering
bp_distributions_no_filtering
dp_distributions_no_filtering
```


### Knee plot with UMI distributions for non-filtered samples 
```{r}
# Knee-plot of the sample Fixed_fresh_K562_noPEG_R1
knee_plot_Fixed_fresh_K562_noPEG_R1_no_filtering <- knee_plot_sample_distribution(experiments_no_filtering, sample = 1, threshold = 0.05)

# Knee-plot of the sample Fixed_fresh_K562_noPEG_R1
total_knee_plot_Fixed_fresh_K562_noPEG_R1_no_filtering <- knee_plot_for_sum_of_sample_wth_sample_distribution(experiments_no_filtering, sample = 1, threshold = 0.05)

knee_plot_Fixed_fresh_K562_noPEG_R1_no_filtering
total_knee_plot_Fixed_fresh_K562_noPEG_R1_no_filtering
```


### Summary metrics for UMI distribution between samples after filtering with EmptyDrops
```{r filtering1, echo=TRUE, fig.height=8, fig.width=10, message=FALSE, warning=FALSE}
# Read the samples, perform the EmptyDrops filtering and create a merged table for all samples
experiments_filtered <- read_10X_samples(counts, barcodes, genes, 
                                   filenames, emptydrops_run = TRUE, fdr_threshold = 0.05)

# Calculate distribution in each barcode
experiments_filtered <- calculate_distributions(experiments_filtered, number_of_samples = 8)

# Assign p-values to Barcodes from the unfiltered dataset 
experiments_filtered <- assign_non_filt_pvals(experiments_filtered, pvals)

# Intersection plot
intersect_plot_filtered <- plot_intersections(experiments_filtered, min_intersection_size = 200)

# Boxplot of distributions
bp_distributions_filtered <- plot_distributions_boxplots(experiments_filtered, number_of_samples = 8, alpha = 0.1)

# Density plot of distributions
dp_distributions_filtered <- plot_distributions_density(experiments_filtered)

intersect_plot_filtered
bp_distributions_filtered
dp_distributions_filtered
```

### Knee plot with UMI distributions for filtered samples 
```{r}
# Knee-plot of the sample Fixed_fresh_K562_noPEG_R1
knee_plot_Fixed_fresh_K562_noPEG_R1_filtered <- knee_plot_sample_distribution(experiments_filtered, sample = 1, threshold = 0.05)

# Knee-plot of the sample Fixed_fresh_K562_noPEG_R1
total_knee_plot_Fixed_fresh_K562_noPEG_R1_filtered <- knee_plot_for_sum_of_sample_wth_sample_distribution(experiments_filtered, sample = 1, threshold = 0.05)

knee_plot_Fixed_fresh_K562_noPEG_R1_filtered
total_knee_plot_Fixed_fresh_K562_noPEG_R1_filtered
```



